(* mathcomp analysis (c) 2026 Inria and AIST. License: CeCILL-C. *)
From HB Require Import structures.
From mathcomp Require Import all_boot all_algebra.
From mathcomp Require Import reals ereal topology classical_sets
  borel_hierarchy measure lebesgue_stieltjes_measure kernel
  probability measurable_realfun lebesgue_measure lebesgue_integral.
From mathcomp Require Import measurable_structure measurable_function
  measure_function probability_measure.
From mathcomp.classical Require Import boolp.
From QBS Require Import quasi_borel probability_qbs qbs_giry
  qbs_kernel measure_qbs_adjunction qbs_fubini.

(**md*************************************************************)
(* # Measurable Structure on Probability Measures               *)
(*                                                               *)
(* This file formalizes the measurable structure on the space    *)
(* of probability measures and connects it to QBS.              *)
(*                                                               *)
(* mathcomp-analysis 1.16.0 already provides:                   *)
(* - [pprobability T R] as a measurableType with sigma-algebra  *)
(*   generated by [pset] = {mset U r | U measurable, r in [0,1]}*)
(* - [kprobability] which builds a probability kernel from a    *)
(*   measurable function to pprobability                         *)
(*                                                               *)
(* We prove:                                                     *)
(* ```                                                           *)
(*   eval_meas == for measurable U, the evaluation map           *)
(*     P |-> P(U) is measurable from pprobability to \bar R     *)
(*   eval_comp_meas == if f : X -> pprobability T R is           *)
(*     measurable, then x |-> f(x)(U) is measurable             *)
(*   pointwise_to_pprobability_meas == pointwise kernel          *)
(*     measurability implies function measurability into          *)
(*     pprobability                                               *)
(*   pprobability_to_pointwise_meas == the converse               *)
(*   pprobability_meas_iff_kernel == the equivalence              *)
(*   giry_kernel_from_g_kernel == kernel measurability on M      *)
(*     reduces to kernel measurability on mR via alpha_Y         *)
(*   giry_family_measurable == the Giry image family is          *)
(*     measurable as mR -> pprobability M R                       *)
(*   kernel_hyp_equiv == qbs_mu_measurable_kernel is equivalent  *)
(*     to pointwise kernel measurability of g                     *)
(*   dirac_family_measurable == the Dirac family is measurable   *)
(*   const_family_measurable == constant families are measurable *)
(*   return_kernel_measurable == Dirac kernel from a measurable  *)
(*     function is measurable                                     *)
(* ```                                                           *)
(*****************************************************************)

Import GRing.Theory Num.Def Num.Theory measurable_realfun.

Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Local Open Scope classical_set_scope.
Local Open Scope ereal_scope.

(* ================================================================== *)
(* Section 1: Evaluation maps are measurable                           *)
(* ================================================================== *)

Section eval_measurable.
Variable R : realType.
Variables (d : measure_display) (T : measurableType d).

(* The evaluation map P |-> P(U) from pprobability T R to \bar R
   is measurable for any measurable U.

   This follows directly from the definition of pprobability:
   its sigma-algebra is generated by the sets
     mset U r = {P | P(U) < r%:E}
   for measurable U and r in [0,1]. The evaluation map's
   preimage of a generator of the Borel sigma-algebra on \bar R
   reduces to a generator of pset.

   This is essentially the content of the measurable_fun_kprobability
   proof in kernel.v. We extract it as a standalone lemma. *)

Lemma eval_meas (U : set T) (mU : measurable U) :
  measurable_fun [set: pprobability T R]
    (fun P : pprobability T R => (P : probability T R) U).
Proof.
apply: (measurability (ErealGenInftyO.G (R:=R))).
- exact: ErealGenInftyO.measurableE.
- move=> _ /= -[_ [r ->] <-].
  rewrite setTI preimage_itvNyo -/(mset U r).
  case: (lerP 0%R r) => r0; last by rewrite lt0_mset//; exact: measurable0.
  case: (lerP r 1%R) => r1; last by rewrite gt1_mset//; exact: measurableT.
  apply: sub_sigma_algebra.
  by exists r => /=; [rewrite in_itv/= r0|exists U].
Qed.

(* ================================================================== *)
(* Section 2: Composition with measurable functions                    *)
(* ================================================================== *)

(* If f : X -> pprobability T R is measurable, then for any
   measurable U, the map x |-> f(x)(U) is measurable. This is
   simply the composition of f with the evaluation map. *)

Lemma eval_comp_meas (d' : measure_display) (X : measurableType d')
    (f : X -> pprobability T R)
    (hf : measurable_fun [set: X] f)
    (U : set T) (mU : measurable U) :
  measurable_fun [set: X]
    (fun x : X => (f x : probability T R) U).
Proof.
apply: measurableT_comp (eval_meas mU) hf.
Qed.

End eval_measurable.

(* ================================================================== *)
(* Section 3: Pointwise kernel measurability <=> pprobability          *)
(*            measurability                                            *)
(* ================================================================== *)

(* The key equivalence: for any function g : X -> probability T R,
   g is measurable as X -> pprobability T R  if and only if
   for each measurable U, the map x |-> g(x)(U) is measurable.

   Direction 1 (pointwise => function): uses the measurability
   lemma to reduce to generators of pset.

   Direction 2 (function => pointwise): composes g with the
   evaluation map via eval_comp_meas. *)

Section pprobability_measurability.
Variable R : realType.
Variables (d : measure_display) (T : measurableType d).
Variables (d' : measure_display) (X : measurableType d').

Variable g : X -> probability T R.

Lemma pointwise_to_pprobability_meas :
  (forall (U : set T), measurable U ->
    measurable_fun setT (fun x => (g x : measure _ _) U)) ->
  measurable_fun [set: X] (g : X -> pprobability T R).
Proof.
move=> hg_kernel.
apply: (measurability
  (@pset _ _ _ : set (set (pprobability T R)))).
- by [].
- move=> A [_ [s s01] [Us mUs <-]] <-.
  rewrite setTI.
  have hm : measurable_fun setT (fun x => (g x : measure _ _) Us).
    exact: hg_kernel.
  have : measurable (setT `&` [set x | (g x : measure _ _) Us < s%:E]).
    exact: emeasurable_fun_infty_o.
  rewrite setTI => h.
  suff -> : g @^-1` [set mu : probability T R | mu Us < s%:E] =
            [set x | (g x : measure _ _) Us < s%:E] by [].
  by apply/seteqP; split => x /=.
Qed.

Lemma pprobability_to_pointwise_meas :
  measurable_fun [set: X] (g : X -> pprobability T R) ->
  forall (U : set T), measurable U ->
    measurable_fun setT (fun x => (g x : measure _ _) U).
Proof.
move=> hg U mU.
have := measurableT_comp (eval_meas mU) hg.
suff -> : (fun x => (g x : probability T R) U) =
          (fun x => (g x : measure _ _) U) by [].
by [].
Qed.

Lemma pprobability_meas_iff_kernel :
  measurable_fun [set: X] (g : X -> pprobability T R) <->
  (forall (U : set T), measurable U ->
    measurable_fun setT (fun x => (g x : measure _ _) U)).
Proof.
split.
- exact: pprobability_to_pointwise_meas.
- exact: pointwise_to_pprobability_meas.
Qed.

End pprobability_measurability.

(* ================================================================== *)
(* Section 4: General measurable type version for the QBS bridge      *)
(* ================================================================== *)

(* For a general measurableType target M with the strong condition,
   kernel measurability on M reduces to kernel measurability on mR
   via the shared random element alpha_Y.

   qbs_to_giry(f(alpha_p(r)))(U)
   = g(r)(alpha_Y^{-1}(U))        [by strong condition]

   So measurability of r |-> qbs_to_giry(...)(U) follows from
   measurability of r |-> g(r)(V) where V = alpha_Y^{-1}(U). *)

Section general_eval.
Variable R : realType.
Local Notation mR := (measurableTypeR R).
Variables (d : measure_display) (M : measurableType d).

Variable (f : mR -> qbs_prob (@R_qbs R _ M)).
Variable (p : qbs_prob (@R_qbs R _ mR)).

Hypothesis hf_strong :
  @qbs_morphism_strong R (@R_qbs R _ mR) (@R_qbs R _ M) f.

(* Decompose the strong condition using case analysis,
   matching the style of qbs_fubini.v. *)

Lemma giry_kernel_from_g_kernel (U : set M) (mU : measurable U) :
  forall alpha_Y : mR -> M,
  forall g : mR -> probability mR R,
  @qbs_Mx R (@R_qbs R _ M) alpha_Y ->
  (forall r, qbs_prob_alpha (f (qbs_prob_alpha p r)) = alpha_Y) ->
  (forall r, qbs_prob_mu (f (qbs_prob_alpha p r)) = g r) ->
  (forall (V : set mR), measurable V ->
    measurable_fun setT (fun r => (g r : measure _ _) V)) ->
  measurable_fun setT
    (fun r => qbs_to_giry (f (qbs_prob_alpha p r)) U).
Proof.
move=> alpha_Y g halpha_Y alpha_eq mu_eq hg_kernel.
have alpha_Y_meas : measurable_fun setT alpha_Y := halpha_Y.
have heq : (fun r => qbs_to_giry (f (qbs_prob_alpha p r)) U) =
           (fun r => (g r : measure _ _) (alpha_Y @^-1` U)).
  apply: boolp.funext => r.
  change (qbs_to_giry_mu (f (qbs_prob_alpha p r)) U =
          (g r : measure _ _) (alpha_Y @^-1` U)).
  by rewrite /qbs_to_giry_mu alpha_eq mu_eq.
rewrite heq.
apply: hg_kernel.
have := alpha_Y_meas measurableT U mU.
by rewrite setTI.
Qed.

(* The full bridge: g-kernel measurability implies measurability
   of the Giry image as a kernel on M. *)
Lemma strong_measurable_giry_kernel
    (alpha_Y : mR -> M) (g0 : mR -> probability mR R)
    (hY : @qbs_Mx R (@R_qbs R _ M) alpha_Y)
    (ha : forall r, qbs_prob_alpha (f (qbs_prob_alpha p r)) = alpha_Y)
    (hm : forall r, qbs_prob_mu (f (qbs_prob_alpha p r)) = g0 r)
    (hg : forall (V : set mR), measurable V ->
      measurable_fun setT (fun r => (g0 r : measure _ _) V))
    (U : set M) (mU : measurable U) :
  measurable_fun setT
    (fun r => qbs_to_giry (f (qbs_prob_alpha p r)) U).
Proof.
apply: (giry_kernel_from_g_kernel mU).
- exact: hY.
- exact: ha.
- exact: hm.
- exact: hg.
Qed.

(* The Giry image family is measurable as mR -> pprobability M R *)
Lemma giry_family_measurable
    (alpha_Y : mR -> M) (g0 : mR -> probability mR R)
    (hY : @qbs_Mx R (@R_qbs R _ M) alpha_Y)
    (ha : forall r, qbs_prob_alpha (f (qbs_prob_alpha p r)) = alpha_Y)
    (hm : forall r, qbs_prob_mu (f (qbs_prob_alpha p r)) = g0 r)
    (hg : forall (V : set mR), measurable V ->
      measurable_fun setT (fun r => (g0 r : measure _ _) V)) :
  measurable_fun [set: mR]
    (fun r => qbs_to_giry (f (qbs_prob_alpha p r)) : pprobability M R).
Proof.
apply: pointwise_to_pprobability_meas => U mU.
apply: (giry_kernel_from_g_kernel mU).
- exact: hY.
- exact: ha.
- exact: hm.
- exact: hg.
Qed.

End general_eval.

(* ================================================================== *)
(* Section 5: The equivalence for the mR -> mR case                    *)
(* ================================================================== *)

(* For f : mR -> qbs_prob(R_qbs mR) satisfying the strong condition,
   the mu component g satisfies qbs_mu_measurable_kernel iff g is
   measurable as mR -> pprobability mR R. *)

Section kernel_equivalence.
Variable R : realType.
Local Notation mR := (measurableTypeR R).

Variable (f : mR -> qbs_prob (@R_qbs R _ mR)).
Variable (p : qbs_prob (@R_qbs R _ mR)).

Hypothesis hf_strong :
  @qbs_morphism_strong R (@R_qbs R _ mR) (@R_qbs R _ mR) f.

Lemma kernel_hyp_equiv :
  forall g : mR -> probability mR R,
  (forall r, qbs_prob_mu (f (qbs_prob_alpha p r)) = g r) ->
  (@qbs_mu_measurable_kernel R (@R_qbs R _ mR) (@R_qbs R _ mR)
    f (qbs_prob_alpha p) <->
  (forall (U : set mR), measurable U ->
    measurable_fun setT (fun r => (g r : measure _ _) U))).
Proof.
move=> g mu_eq; split.
- move=> hkernel U mU.
  have := hkernel U mU.
  suff -> : (fun r => qbs_prob_mu (f (qbs_prob_alpha p r)) U) =
            (fun r => (g r : measure _ _) U) by [].
  by apply: boolp.funext => r; rewrite mu_eq.
- move=> hg U mU.
  have := hg U mU.
  suff -> : (fun r => (g r : measure _ _) U) =
            (fun r => qbs_prob_mu (f (qbs_prob_alpha p r)) U) by [].
  by apply: boolp.funext => r; rewrite mu_eq.
Qed.

(* The bridge from pprobability measurability to qbs_mu_measurable_kernel *)
Lemma qbs_mu_kernel_from_pprobability_meas :
  forall g : mR -> probability mR R,
  (forall r, qbs_prob_mu (f (qbs_prob_alpha p r)) = g r) ->
  measurable_fun [set: mR] (g : mR -> pprobability mR R) ->
  @qbs_mu_measurable_kernel R (@R_qbs R _ mR) (@R_qbs R _ mR)
    f (qbs_prob_alpha p).
Proof.
move=> g mu_eq hg.
apply/(kernel_hyp_equiv mu_eq).
exact: pprobability_to_pointwise_meas hg.
Qed.

(* The bridge from qbs_mu_measurable_kernel to pprobability measurability *)
Lemma pprobability_meas_from_qbs_mu_kernel :
  forall g : mR -> probability mR R,
  (forall r, qbs_prob_mu (f (qbs_prob_alpha p r)) = g r) ->
  @qbs_mu_measurable_kernel R (@R_qbs R _ mR) (@R_qbs R _ mR)
    f (qbs_prob_alpha p) ->
  measurable_fun [set: mR] (g : mR -> pprobability mR R).
Proof.
move=> g mu_eq hkernel.
apply: pointwise_to_pprobability_meas.
by apply/(kernel_hyp_equiv mu_eq).
Qed.

(* Building a probability kernel from the strong condition *)
Lemma strong_prob_kernel_build :
  forall g : mR -> probability mR R,
  (forall r, qbs_prob_mu (f (qbs_prob_alpha p r)) = g r) ->
  (forall (U : set mR), measurable U ->
    measurable_fun setT (fun r => (g r : measure _ _) U)) ->
  { mP : measurable_fun [set: mR] (g : mR -> pprobability mR R) |
    forall r U, kprobability mP r U = (g r : measure _ _) U }.
Proof.
move=> g mu_eq hg.
have mP := pointwise_to_pprobability_meas hg.
by exists mP.
Qed.

End kernel_equivalence.

(* ================================================================== *)
(* Section 6: Instances for specific constructions                     *)
(* ================================================================== *)

(* For specific QBS constructions, we can verify the kernel
   measurability hypothesis directly, without assuming it. *)

Section specific_instances.
Variable R : realType.
Local Notation mR := (measurableTypeR R).

(* The Dirac family r |-> dirac(r) is measurable as
   mR -> pprobability mR R *)
Lemma dirac_family_measurable :
  measurable_fun [set: mR] (fun r : mR => dirac r : pprobability mR R).
Proof.
apply: pointwise_to_pprobability_meas => U mU.
(* dirac(r)(U) = (\1_U r)%:E = EFin (indic U r) *)
have -> : (fun x : mR => (dirac x : measure _ _) U) =
          EFin \o (fun r : mR => numfun.indic U r : R).
  by apply: boolp.funext => r; rewrite /= /dirac.
apply/measurable_EFinP.
apply: measurable_indic => //.
Qed.

(* Kernel measurability of the Dirac family *)
Lemma dirac_kernel_measurable (U : set mR) (mU : measurable U) :
  measurable_fun setT (fun r : mR => @dirac _ mR r R U).
Proof.
have := pprobability_to_pointwise_meas dirac_family_measurable mU.
suff -> : (fun x : mR => (dirac x : probability mR R) U) =
          (fun x : mR => @dirac _ mR x R U) by [].
by [].
Qed.

(* For a constant family (e.g., from sample): *)
Lemma const_family_measurable (P : probability mR R) :
  measurable_fun [set: mR] (fun _ : mR => P : pprobability mR R).
Proof.
exact: measurable_cst.
Qed.

(* Kernel measurability of the constant family *)
Lemma const_kernel_measurable (P : probability mR R) (U : set mR) :
  measurable U ->
  measurable_fun setT (fun _ : mR => (P : measure _ _) U).
Proof.
by move=> _; exact: measurable_cst.
Qed.

(* For qbs_return composed with a measurable function:
   g(r) = dirac(h(r)) for measurable h : mR -> mR.
   The kernel measurability: r |-> dirac(h(r))(U) = 1_U(h(r))
   is measurable because h is measurable and 1_U is measurable. *)

Lemma return_kernel_measurable (h : mR -> mR)
    (hm : measurable_fun setT h) (U : set mR) (mU : measurable U) :
  measurable_fun setT (fun r : mR => @dirac _ mR (h r) R U).
Proof.
(* dirac(h(r))(U) = (\1_U (h r))%:E = EFin (indic U (h r)) *)
have -> : (fun r : mR => @dirac _ mR (h r) R U) =
          EFin \o (numfun.indic U \o h).
  by apply: boolp.funext => r; rewrite /= /dirac.
apply/measurable_EFinP.
apply: measurableT_comp; last exact: hm.
exact: measurable_indic.
Qed.

(* The Dirac family composed with a measurable function *)
Lemma dirac_comp_family_measurable (h : mR -> mR)
    (hm : measurable_fun setT h) :
  measurable_fun [set: mR]
    (fun r : mR => @dirac _ mR (h r) R : pprobability mR R).
Proof.
apply: pointwise_to_pprobability_meas.
exact: return_kernel_measurable hm.
Qed.

End specific_instances.

(* ================================================================== *)
(* Section 7: Summary and the full bridge                              *)
(* ================================================================== *)

(* SUMMARY
   ========

   The space pprobability T R of probability measures on a measurable
   type T already has a sigma-algebra in mathcomp-analysis (generated
   by pset = {mset U r | U measurable, r in [0,1]}). We proved:

   1. EVALUATION MAPS ARE MEASURABLE (eval_meas):
      For measurable U, the map P |-> P(U) is measurable from
      pprobability T R to \bar R.

   2. COMPOSITION PRESERVES MEASURABILITY (eval_comp_meas):
      If f : X -> pprobability T R is measurable, then for any
      measurable U, x |-> f(x)(U) is measurable.

   3. POINTWISE <=> FUNCTION MEASURABILITY (pprobability_meas_iff_kernel):
      g : X -> probability T R is measurable as X -> pprobability T R
      if and only if x |-> g(x)(U) is measurable for each measurable U.

   4. QBS BRIDGE (kernel_hyp_equiv):
      For f : mR -> qbs_prob(R_qbs mR) satisfying the strong condition
      with witness g, qbs_mu_measurable_kernel(f) is equivalent to
      pointwise kernel measurability of g.

   5. GIRY KERNEL REDUCTION (giry_kernel_from_g_kernel):
      For a general target M, kernel measurability of the Giry image
      qbs_to_giry(f(alpha_p(r)))(U) reduces to kernel measurability
      of g on alpha_Y-preimages (which are fixed measurable sets).

   6. SPECIFIC INSTANCES:
      - Dirac family: always measurable (dirac_family_measurable)
      - Constant family: always measurable (const_family_measurable)
      - Dirac composed with measurable function: measurable
        (dirac_comp_family_measurable)

   The key architectural insight is that pprobability measurability
   and pointwise kernel measurability are EQUIVALENT
   (pprobability_meas_iff_kernel). This means:
   - The hypothesis qbs_mu_measurable_kernel from qbs_fubini.v
     can be reformulated as measurability into pprobability.
   - kprobability from kernel.v can be applied once we have
     pprobability measurability.
   - For specific constructions (return, sample), measurability
     can be verified directly without any hypothesis. *)
