(* mathcomp analysis (c) 2026 Inria and AIST. License: CeCILL-C.              *)

(**md**************************************************************************)
(* # Analysis: Strengthening monadP_random with Measurability                 *)
(*                                                                            *)
(* Investigation of whether the monadP_random definition should be            *)
(* strengthened to require measurability of the measure component g,          *)
(* and the practical feasibility of such a change.                            *)
(*                                                                            *)
(* ## 1. Mathematical soundness                                               *)
(*                                                                            *)
(* The HKSY paper (LICS 2017, Def 22) defines the probability monad          *)
(* P(X) on a QBS X as follows. A random element of P(X) is a                 *)
(* function beta : R -> (alpha, mu) where:                                    *)
(*   - There exists a SINGLE alpha in M_X (shared across all r)               *)
(*   - There exists a function g : R -> Prob(R) such that for all r,          *)
(*     beta(r) = (alpha, g(r))                                                *)
(*                                                                            *)
(* The paper states that alpha and mu(r) must "vary measurably"               *)
(* (Proposition 22.3), but the FORMAL definition in Def 22 only              *)
(* quantifies existentially over alpha and g with no measurability            *)
(* constraint on g. This is because:                                          *)
(*                                                                            *)
(* (a) The QBS axioms (composition, constant, gluing) for P(X) are           *)
(*     formulated using monadP_random_pw (the WEAK pointwise                  *)
(*     condition), not the strong condition. The weak condition               *)
(*     suffices to show that P(X) forms a QBS.                                *)
(*                                                                            *)
(* (b) The strong condition (monadP_random) is used for bind's               *)
(*     diagonal extraction, where only the shared alpha matters.              *)
(*     The measure component g is existentially quantified but                *)
(*     NEVER used in the diagonal extraction proof                            *)
(*     (qbs_bind_alpha_random_strong).                                        *)
(*                                                                            *)
(* (c) Measurability of g becomes relevant ONLY when connecting              *)
(*     the QBS monad to the Giry monad (kernel semantics). The               *)
(*     HKSY paper proves this connection via Proposition 22.3                 *)
(*     using the standard Borel property, which implies that g               *)
(*     IS measurable -- but this is a THEOREM about standard                  *)
(*     Borel spaces, not part of the definition.                              *)
(*                                                                            *)
(* Therefore: adding measurability of g to monadP_random is a                *)
(* GENUINE STRENGTHENING of the definition, not merely making                 *)
(* implicit information explicit. It is mathematically sound                  *)
(* (the strengthened definition still defines a valid monad on                *)
(* standard Borel QBS), but it changes the logical structure.                 *)
(*                                                                            *)
(* ## 2. Impact analysis                                                      *)
(*                                                                            *)
(* monadP_random appears in exactly 3 roles:                                  *)
(*                                                                            *)
(* (A) DEFINITION (probability_qbs.v:105): the definition itself              *)
(*                                                                            *)
(* (B) DESTRUCTOR (probability_qbs.v:124, monadP_random_impl):               *)
(*     Extracts monadP_random_pw from monadP_random.                          *)
(*     Impact: NONE -- the measurability clause is simply ignored.            *)
(*                                                                            *)
(* (C) CONSTRUCTOR via qbs_morphism_strong (probability_qbs.v:234):           *)
(*     qbs_morphism_strong X Y f :=                                           *)
(*       forall alpha, qbs_Mx alpha -> monadP_random Y (f o alpha)            *)
(*     Every proof of qbs_morphism_strong constructs a monadP_random          *)
(*     witness. These proofs must be updated to discharge the new             *)
(*     measurability obligation.                                              *)
(*                                                                            *)
(* (D) DESTRUCTOR via qbs_bind_alpha_random_strong                            *)
(*     (probability_qbs.v:240):                                               *)
(*     Extracts alpha_Y and uses qbs_Mx alpha_Y.                              *)
(*     The g component is destructed but DISCARDED (lines 245-249).           *)
(*     Impact: NONE -- the measurability clause would be available            *)
(*     but not needed.                                                        *)
(*                                                                            *)
(* (E) DESTRUCTOR in qbs_fubini.v and qbs_bind_kernel.v:                      *)
(*     These files extract g and alpha_Y from the strong condition.           *)
(*     They ALREADY assume g-measurability as a SEPARATE hypothesis           *)
(*     (g_kernel_meas / hf_kernel). With the strengthened definition,         *)
(*     this hypothesis would be derivable from the strong condition           *)
(*     itself, ELIMINATING the need for the separate hypothesis.              *)
(*                                                                            *)
(* ## 3. Affected lemmas and feasibility                                      *)
(*                                                                            *)
(* ### 3a. Constructors of qbs_morphism_strong (must discharge new            *)
(*         measurability obligation)                                          *)
(*                                                                            *)
(* (i) likelihood_single_strong (bayesian_regression.v:226)                   *)
(*     g(r) = normal_prob (fst(alpha(r)) * obs_x + snd(alpha(r)))             *)
(*                          noise_sigma                                       *)
(*     Measurability obligation: for measurable U,                            *)
(*       r |-> normal_prob(fst(alpha(r))*obs_x + snd(alpha(r)), s)(U)         *)
(*     is measurable.                                                         *)
(*     This requires showing that the normal distribution's measure           *)
(*     function varies measurably with its mean parameter. Feasible           *)
(*     in principle (the Radon-Nikodym derivative normal_pdf is               *)
(*     measurable in the mean parameter) but NONTRIVIAL to prove              *)
(*     in the current infrastructure.                                         *)
(*     Verdict: HARD but feasible.                                            *)
(*                                                                            *)
(* (ii) Any future proofs of qbs_morphism_strong for sampling                 *)
(*      distributions (e.g., normal, uniform, Bernoulli parameterized         *)
(*      by a random element). Each would need to show that the                *)
(*      parameterized distribution varies measurably.                         *)
(*      Verdict: Case-by-case. Feasible for standard distributions.           *)
(*                                                                            *)
(* ### 3b. Destructors of monadP_random (benefit from strengthening)          *)
(*                                                                            *)
(* (i) qbs_bind_alpha_random_strong (probability_qbs.v:240)                   *)
(*     No change needed. The new clause is available but unused.              *)
(*                                                                            *)
(* (ii) monadP_random_impl (probability_qbs.v:123)                            *)
(*      No change needed.                                                     *)
(*                                                                            *)
(* (iii) qbs_fubini.v: qbs_strong_measurable_kernel (line 127)                *)
(*       Currently takes hf_kernel as a SEPARATE hypothesis.                  *)
(*       With strengthened monadP_random, hf_kernel can be DERIVED            *)
(*       from hf_strong, eliminating the hypothesis.                          *)
(*       Verdict: BENEFIT -- cleaner API.                                     *)
(*                                                                            *)
(* (iv) qbs_bind_kernel.v: g_kernel_meas (line 103)                           *)
(*      Currently a separate hypothesis. With strengthened definition,        *)
(*      derivable from hf_strong.                                             *)
(*      Verdict: BENEFIT -- cleaner API.                                      *)
(*                                                                            *)
(* ### 3c. Unaffected lemmas                                                  *)
(*                                                                            *)
(* All lemmas using only monadP_random_pw (the pointwise condition):          *)
(* monadP_comp, monadP_const, monadP_glue, monadP definition,                *)
(* qbs_return_random, qbs_bind_returnl, qbs_bind_returnr, qbs_bindA,         *)
(* all integration lemmas, all congruence lemmas, all strength lemmas,        *)
(* all inequality lemmas, normalization lemmas.                               *)
(* Verdict: NO CHANGE.                                                        *)
(*                                                                            *)
(* ## 4. Alternative: strengthen qbs_morphism_strong instead                  *)
(*                                                                            *)
(* Instead of changing monadP_random globally, we could define:               *)
(*   qbs_morphism_strong_meas X Y f :=                                        *)
(*     forall alpha, qbs_Mx alpha ->                                          *)
(*       exists alpha_Y g,                                                    *)
(*         qbs_Mx alpha_Y /\                                                  *)
(*         (forall r, qbs_prob_alpha ((f o alpha) r) = alpha_Y) /\            *)
(*         (forall r, qbs_prob_mu ((f o alpha) r) = g r) /\                   *)
(*         (forall U, measurable U ->                                         *)
(*           measurable_fun setT (fun r => g r U))                            *)
(*                                                                            *)
(* Pros:                                                                      *)
(* - Less invasive: monadP_random itself is unchanged                         *)
(* - Only affects files that use qbs_morphism_strong                          *)
(* - Backward compatible: old proofs of qbs_morphism_strong                   *)
(*   do NOT need updating (they prove the weaker version)                     *)
(* - Can coexist: both strong and strong_meas can live in parallel            *)
(*                                                                            *)
(* Cons:                                                                      *)
(* - Two flavors of "strong" is confusing                                     *)
(* - The measurability is a property of the FAMILY beta, not of               *)
(*   the morphism f per se; conceptually it belongs on monadP_random          *)
(* - Downstream files (qbs_fubini.v, qbs_bind_kernel.v) would still           *)
(*   need to be updated to use the new version                                *)
(*                                                                            *)
(* Verdict: This is MORE FEASIBLE as a migration strategy. The                *)
(* recommended approach is:                                                   *)
(*                                                                            *)
(*   Phase 1: Define qbs_morphism_strong_meas alongside the existing          *)
(*            qbs_morphism_strong. Prove a coercion:                          *)
(*              strong_meas -> strong                                         *)
(*            Update qbs_fubini.v and qbs_bind_kernel.v to use                *)
(*            qbs_morphism_strong_meas, eliminating their separate            *)
(*            g-measurability hypotheses.                                     *)
(*                                                                            *)
(*   Phase 2: Prove qbs_morphism_strong_meas for concrete instances           *)
(*            (likelihood_single, any future sampling distributions).         *)
(*                                                                            *)
(*   Phase 3: Once all uses of qbs_morphism_strong are upgraded,              *)
(*            optionally fold the measurability into monadP_random            *)
(*            itself.                                                         *)
(*                                                                            *)
(* ## 5. Concrete migration plan                                              *)
(*                                                                            *)
(* Step 1 (probability_qbs.v):                                                *)
(*   - Add monadP_random_meas alongside monadP_random                         *)
(*   - Add qbs_morphism_strong_meas alongside qbs_morphism_strong             *)
(*   - Prove: monadP_random_meas -> monadP_random (forgetful)                 *)
(*   - Prove: qbs_morphism_strong_meas -> qbs_morphism_strong                 *)
(*   - Add qbs_bind_alpha_random_strong_meas that additionally                *)
(*     returns the g-measurability witness                                    *)
(*   ~20 lines of new definitions, ~10 lines of coercion proofs.              *)
(*                                                                            *)
(* Step 2 (qbs_fubini.v):                                                     *)
(*   - Replace (hf_strong + hf_kernel) with hf_strong_meas                    *)
(*   - Derive the old hf_kernel from hf_strong_meas internally                *)
(*   ~5 lines changed per section (2 sections).                               *)
(*                                                                            *)
(* Step 3 (qbs_bind_kernel.v):                                                *)
(*   - Replace (hf + g_kernel_meas) with hf_strong_meas                       *)
(*   - Derive g_kernel_meas from hf_strong_meas internally                    *)
(*   ~5 lines changed per section (2 sections).                               *)
(*                                                                            *)
(* Step 4 (bayesian_regression.v):                                            *)
(*   - Upgrade likelihood_single_strong to likelihood_single_strong_meas      *)
(*   - Requires proving: for measurable U,                                    *)
(*     r |-> normal_prob(linear_mean(alpha(r)), noise_sigma)(U)               *)
(*     is measurable.                                                         *)
(*   This is the HARD step. Estimated ~50-100 lines for the                   *)
(*   parametric measurability of normal_prob.                                 *)
(*                                                                            *)
(* Total effort: ~50 lines straightforward + ~50-100 lines hard               *)
(* (parametric measurability of normal_prob).                                 *)
(*                                                                            *)
(* ## 6. Recommendation                                                       *)
(*                                                                            *)
(* The phased approach (define qbs_morphism_strong_meas alongside             *)
(* the existing definitions, then migrate incrementally) is                   *)
(* recommended. Key reasons:                                                  *)
(*                                                                            *)
(* (a) It is non-breaking: all existing proofs continue to work.              *)
(*                                                                            *)
(* (b) It gives immediate benefit: qbs_fubini.v and                           *)
(*     qbs_bind_kernel.v can drop their separate g-measurability              *)
(*     hypotheses, getting cleaner theorem statements.                        *)
(*                                                                            *)
(* (c) The hard part (parametric measurability of distributions)              *)
(*     is isolated to step 4 and can be done independently.                   *)
(*                                                                            *)
(* (d) The strengthening is mathematically justified: on standard             *)
(*     Borel spaces (which is the only case of practical interest),           *)
(*     measurability of g is a theorem (HKSY Prop 22.3), so                   *)
(*     requiring it upfront does not lose generality.                         *)
(******************************************************************************)
